apiVersion: v1
kind: Secret
metadata:
  name: titan-secrets
  namespace: titan-banking
type: Opaque
stringData:
  JWT_SECRET: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
  DB_PASSWORD: "TitanDB$ecure2026_X9z!Lp"
  REDIS_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: titan-db-secret
  namespace: titan-banking
type: Opaque
stringData:
  postgres-password: "TitanDB$ecure2026_X9z!Lp"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: titan-config
  namespace: titan-banking
data:
  JWT_ISSUER: "titan-banking"
  JWT_AUDIENCE: "titan-api"
  SPRING_PROFILES_ACTIVE: "prod"
